Update webmock
```
Failure/Error: visit "/#{secret_page.url_key}"

NoMethodError:
  undefined method `<<' for {:read_timeout=>60, :continue_timeout=>nil, :debug_output=>nil}:Hash
  Did you mean?  <
 /Users/adrian.cann/.rvm/gems/ruby-2.5.1/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/net_http.rb:97:in `block in request'
 /Users/adrian.cann/.rvm/gems/ruby-2.5.1/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/net_http.rb:105:in `block in request'
 /Users/adrian.cann/.rvm/gems/ruby-2.5.1/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/net_http.rb:137:in `start_with_connect_without_finish'
 /Users/adrian.cann/.rvm/gems/ruby-2.5.1/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/net_http.rb:104:in `request'
 /Users/adrian.cann/.rvm/gems/ruby-2.5.1/gems/capybara-2.7.1/lib/capybara/server.rb:82:in `block in responsive?'
 /Users/adrian.cann/.rvm/gems/ruby-2.5.1/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/net_http.rb:123:in `start_without_connect'
 /Users/adrian.cann/.rvm/gems/ruby-2.5.1/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/net_http.rb:150:in `start'
 /Users/adrian.cann/.rvm/gems/ruby-2.5.1/gems/capybara-2.7.1/lib/capybara/server.rb:82:in `responsive?'
 /Users/adrian.cann/.rvm/gems/ruby-2.5.1/gems/capybara-2.7.1/lib/capybara/server.rb:98:in `boot'
 /Users/adrian.cann/.rvm/gems/ruby-2.5.1/gems/capybara-2.7.1/lib/capybara/session.rb:72:in `initialize'
 /Users/adrian.cann/.rvm/gems/ruby-2.5.1/gems/capybara-2.7.1/lib/capybara.rb:321:in `new'
 /Users/adrian.cann/.rvm/gems/ruby-2.5.1/gems/capybara-2.7.1/lib/capybara.rb:321:in `current_session'
 /Users/adrian.cann/.rvm/gems/ruby-2.5.1/gems/capybara-2.7.1/lib/capybara/dsl.rb:47:in `page'
 /Users/adrian.cann/.rvm/gems/ruby-2.5.1/gems/capybara-2.7.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
 ./spec/features/visit_secret_page_spec.rb:23:in `block (2 levels) in <top (required)>'
```